services:
  postgres:
    image: postgres:16-alpine
    container_name: adm_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: adm_db
      POSTGRES_USER: adm_user
      POSTGRES_PASSWORD: adm_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - adm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adm_user -d adm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: adm_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - adm_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  adm_network:
    driver: bridge