name: Release Version Increment

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository (with full history)
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Ensure tags are available
              run: git fetch --tags --force --prune

            - name: Calculate next version (Conventional Commits)
              id: version
              uses: reecetech/version-increment@2024.10.1
              with:
                  scheme: conventional_commits
                  increment: patch
                  # release_branch: main       # Uncomment if your release branch is not the default
                  # tag_prefix: ''            # e.g. '@org/app/' in monorepo

            - name: Show computed versions
              run: |
                  echo "current: ${{ steps.version.outputs['current-version'] }}"
                  echo "next:    ${{ steps.version.outputs.version }}"
                  echo "v-next:  ${{ steps.version.outputs['v-version'] }}"

            - name: Create and push tag
              if: github.ref == 'refs/heads/main'
              env:
                  VERSION: ${{ steps.version.outputs['v-version'] }}
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  if git rev-parse "$VERSION" >/dev/null 2>&1; then
                    echo "Tag $VERSION already exists, skipping creation."
                  else
                    git tag -a "$VERSION" -m "chore(release): $VERSION"
                  fi
                  git push origin "$VERSION"
